[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
forge-std = "1.9.4"
"@openzeppelin-contracts" = "5.2.0-rc.0"

remappings= [
"@openzeppelin-contracts-5.2.0-rc.0/=dependencies/@openzeppelin-contracts-5.2.0-rc.0/",
"forge-std-1.9.4/=dependencies/forge-std-1.9.4/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
